apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/configMap: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ngrok
          image: wernight/ngrok:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
            - configMapRef:
                name: {{ .Release.Name }}-configmap
